CAPSTONE PROJECT
JacintaNgwu/JavaScript-Capstone-Project pull request #11
Opened 2023-01-13 20:32 UTC by Dmambo

# Features Implemented💻

- Used an external API(TVMAZE API) ✔
- Used an Involvement API to get likes and comment✔
- Set up project with WEBPACK and JEST✔
- Added header and footer✔
- Displayed list of items on the homepage✔
- Added all item counter for the whole items✔
- Added the feature to add new like and display likes✔

![image](https://user-images.githubusercontent.com/100554236/212406823-3fb6cccf-d5a0-4132-a6f5-8cb0ee380c21.png)

- created a popup window to show the item details✔

![image](https://user-images.githubusercontent.com/100554236/212407386-312008b2-3353-44fd-9de4-00f4846e3d98.png)
![image](https://user-images.githubusercontent.com/100554236/212407468-f5356efa-928d-4c10-a573-dac421bf0133.png)

- Container to display comments✔

![image](https://user-images.githubusercontent.com/100554236/212407584-bfb562aa-03fa-43b4-b6a9-14aa432818b5.png)

- Form to add comment ✔

![image](https://user-images.githubusercontent.com/100554236/212407699-3ad627bf-32bd-4706-9668-4cfb618d4aa0.png)

- Added test files to test for comment counter and item counter✔

![image](https://user-images.githubusercontent.com/100554236/212378556-5ba52a23-a14e-4973-b9e3-526203263d28.png)

2023-01-13 21:08 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Dmambo and @JacintaNgwu,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-13 21:08 UTC, omar-muhamad commented on src/index.js
> +// const itemCount = document.querySelector('.item-counter');
- [ ] It would be better professionally if you remove uncommented code to make your code more readable and clean.

2023-01-13 21:08 UTC, Omar-Muhamad commented on src/index.js
> +              // eslint-disable-next-line implicit-arrow-linebreak
- [ ] Please remove this linters disablement line and fix all eslint issues yourself.

2023-01-13 21:08 UTC, Omar-Muhamad commented on src/modules/api.js
> +// export const MOVIE_API = 'https://api.tvmaze.com/shows';
- [ ] Please remove this module because there is no code used on it.

2023-01-13 21:08 UTC, Omar-Muhamad commented on src/modules/comment/addcomment.js
> +/* eslint-disable operator-linebreak */
- [ ] Same here, Please remove this linters disablement line and fix all eslint issues yourself.

2023-01-13 21:08 UTC, Omar-Muhamad commented on src/modules/comment/commentCounter.test.js
> +// const commentCounter = require('./commentCounter.js');
- [ ] Same here, Please remove uncommented code to make your code more readable and clean.

2023-01-13 21:08 UTC, Omar-Muhamad commented on src/modules/comment/getcomment.js
> +const BASE_URL =
- [ ] Same here, Please remove this linters disablement line and fix all eslint issues yourself.

2023-01-13 21:08 UTC, Omar-Muhamad commented on src/modules/itemCounter.js
> +// import getShows from '../index.js';
- [ ] Same here, Please remove this linters disablement line and fix all eslint issues yourself.

2023-01-13 21:08 UTC, Omar-Muhamad commented on src/modules/likes.js
> +const BASE_URL =
- [ ] Same here, Please remove this linters disablement line and fix all eslint issues yourself.

2023-01-14 05:05 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Dmambo and @JacintaNgwu 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
-  **[OPTIONAL]** **RECOMMENDED:** **Kindly make sure you remove the Microverse **template logo** from your README. Optionally, you can replace it with your own logo if you have one. This was supposed to be mentioned by the previous reviewer and even invalidate your project**

- **[OPTIONAL]** **RECOMMENDED:** I think it would be better if you fix the broken `[MIT](./LICENSE)` link in your README file to make it more professional as it shows a **404** error page once clicked. And to fix that, you can only create a new file name `LICENSE` in your root directory and get its content from this **[template](https://github.com/microverseinc/readme-template/blob/master/MIT.md)** or rename this `[MIT](./LICENSE)` to `[MIT](./MIT.md)`, then the created file in your directory name it `MIT.md` and use the same comment in this **[template](https://github.com/microverseinc/readme-template/blob/master/MIT.md)**

- **[OPTIONAL]** **RECOMMENDED:** Please make sure you add the section `Future Features` in your README, and it should include 1-3 potential features to be added. This was supposed to be mentioned by the previous reviewer and and missing this section in your next projects can cause an invalidation your project

_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Notice
**I didn't invalidate this PR because I referred to this **[advice](https://microverse-crs.slack.com/archives/CM454ATKJ/p1673549161873099)** from Sr. CRS**

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 05:05 UTC, tresorsawasawa commented on .babelrc
> +
- [ **OPTIONAL** ] I think it would b better if you remove all the commented and unused code lines from your code base to make it readable and clean.

2023-01-14 06:38 UTC, merged